"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.psm_cloud.model.cluster_key_value import ClusterKeyValue


class TestClusterKeyValue(unittest.TestCase):
    """ClusterKeyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterKeyValue(self):
        """Test ClusterKeyValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterKeyValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
