"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.api_list_meta import ApiListMeta
from pensando_cloud.psm_cloud.model.network_service import NetworkService
globals()['ApiListMeta'] = ApiListMeta
globals()['NetworkService'] = NetworkService
from pensando_cloud.psm_cloud.psm_cloud.model.network_service_list import NetworkServiceList


class TestNetworkServiceList(unittest.TestCase):
    """NetworkServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkServiceList(self):
        """Test NetworkServiceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkServiceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
