"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.api_object_meta import ApiObjectMeta
from pensando_cloud.psm_cloud.model.network_route_table_status import NetworkRouteTableStatus
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['NetworkRouteTableStatus'] = NetworkRouteTableStatus
from pensando_cloud.psm_cloud.psm_cloud.model.network_route_table import NetworkRouteTable


class TestNetworkRouteTable(unittest.TestCase):
    """NetworkRouteTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkRouteTable(self):
        """Test NetworkRouteTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkRouteTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
