"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.network_dhcp_server import NetworkDHCPServer
globals()['NetworkDHCPServer'] = NetworkDHCPServer
from pensando_cloud.psm_cloud.psm_cloud.model.network_dhcp_relay_policy import NetworkDHCPRelayPolicy


class TestNetworkDHCPRelayPolicy(unittest.TestCase):
    """NetworkDHCPRelayPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkDHCPRelayPolicy(self):
        """Test NetworkDHCPRelayPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkDHCPRelayPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
