"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.network_rd_spec import NetworkRDSpec
globals()['NetworkRDSpec'] = NetworkRDSpec
from pensando_cloud.psm_cloud.psm_cloud.model.network_virtual_router_spec import NetworkVirtualRouterSpec


class TestNetworkVirtualRouterSpec(unittest.TestCase):
    """NetworkVirtualRouterSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkVirtualRouterSpec(self):
        """Test NetworkVirtualRouterSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkVirtualRouterSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
