"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.auth_permission import AuthPermission
globals()['AuthPermission'] = AuthPermission
from pensando_cloud.psm_cloud.psm_cloud.model.auth_role_spec import AuthRoleSpec


class TestAuthRoleSpec(unittest.TestCase):
    """AuthRoleSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthRoleSpec(self):
        """Test AuthRoleSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthRoleSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
