"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.psm_cloud.model.network_route_distinguisher import NetworkRouteDistinguisher


class TestNetworkRouteDistinguisher(unittest.TestCase):
    """NetworkRouteDistinguisher unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkRouteDistinguisher(self):
        """Test NetworkRouteDistinguisher"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkRouteDistinguisher()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
