"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_cloud
from pensando_cloud.psm_cloud.model.api_object_meta import ApiObjectMeta
globals()['ApiObjectMeta'] = ApiObjectMeta
from pensando_cloud.psm_cloud.psm_cloud.model.auth_password_change_request import AuthPasswordChangeRequest


class TestAuthPasswordChangeRequest(unittest.TestCase):
    """AuthPasswordChangeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPasswordChangeRequest(self):
        """Test AuthPasswordChangeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPasswordChangeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
