"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.psm_ent.model.api_label import ApiLabel


class TestApiLabel(unittest.TestCase):
    """ApiLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiLabel(self):
        """Test ApiLabel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiLabel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
