"""
    Aggwatch API reference

       # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.psm_ent.model.api_list_watch_options import ApiListWatchOptions


class TestApiListWatchOptions(unittest.TestCase):
    """ApiListWatchOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListWatchOptions(self):
        """Test ApiListWatchOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiListWatchOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
