"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.api_bgp_asn import ApiBgpAsn
from pensando_ent.psm_ent.model.network_bgp_neighbor import NetworkBGPNeighbor
globals()['ApiBgpAsn'] = ApiBgpAsn
globals()['NetworkBGPNeighbor'] = NetworkBGPNeighbor
from pensando_ent.psm_ent.psm_ent.model.network_bgp_config import NetworkBGPConfig


class TestNetworkBGPConfig(unittest.TestCase):
    """NetworkBGPConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkBGPConfig(self):
        """Test NetworkBGPConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkBGPConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
