"""
    Browser API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.api_object_meta import ApiObjectMeta
from pensando_ent.psm_ent.model.browser_browse_request_object import BrowserBrowseRequestObject
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['BrowserBrowseRequestObject'] = BrowserBrowseRequestObject
from pensando_ent.psm_ent.psm_ent.model.browser_browse_request_list import BrowserBrowseRequestList


class TestBrowserBrowseRequestList(unittest.TestCase):
    """BrowserBrowseRequestList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrowserBrowseRequestList(self):
        """Test BrowserBrowseRequestList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BrowserBrowseRequestList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
