"""
    Preferences API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.api_object_meta import ApiObjectMeta
from pensando_ent.psm_ent.model.preferences_ui_global_settings_spec import PreferencesUIGlobalSettingsSpec
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['PreferencesUIGlobalSettingsSpec'] = PreferencesUIGlobalSettingsSpec
from pensando_ent.psm_ent.psm_ent.model.preferences_ui_global_settings import PreferencesUIGlobalSettings


class TestPreferencesUIGlobalSettings(unittest.TestCase):
    """PreferencesUIGlobalSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferencesUIGlobalSettings(self):
        """Test PreferencesUIGlobalSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PreferencesUIGlobalSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
