"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.auth_role import AuthRole
globals()['AuthRole'] = AuthRole
from pensando_ent.psm_ent.psm_ent.model.auth_auto_msg_role_watch_helper_watch_event import AuthAutoMsgRoleWatchHelperWatchEvent


class TestAuthAutoMsgRoleWatchHelperWatchEvent(unittest.TestCase):
    """AuthAutoMsgRoleWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthAutoMsgRoleWatchHelperWatchEvent(self):
        """Test AuthAutoMsgRoleWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthAutoMsgRoleWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
