"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.labels_selector import LabelsSelector
globals()['LabelsSelector'] = LabelsSelector
from pensando_ent.psm_ent.psm_ent.model.monitoring_instance_selector import MonitoringInstanceSelector


class TestMonitoringInstanceSelector(unittest.TestCase):
    """MonitoringInstanceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringInstanceSelector(self):
        """Test MonitoringInstanceSelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringInstanceSelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
