"""
    Workload API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.model.workload_endpoint import WorkloadEndpoint
globals()['WorkloadEndpoint'] = WorkloadEndpoint
from pensando_ent.psm_ent.psm_ent.model.workload_auto_msg_endpoint_watch_helper_watch_event import WorkloadAutoMsgEndpointWatchHelperWatchEvent


class TestWorkloadAutoMsgEndpointWatchHelperWatchEvent(unittest.TestCase):
    """WorkloadAutoMsgEndpointWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkloadAutoMsgEndpointWatchHelperWatchEvent(self):
        """Test WorkloadAutoMsgEndpointWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkloadAutoMsgEndpointWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
