"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_ent
from pensando_ent.psm_ent.psm_ent.model.monitoring_audit_info import MonitoringAuditInfo


class TestMonitoringAuditInfo(unittest.TestCase):
    """MonitoringAuditInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAuditInfo(self):
        """Test MonitoringAuditInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAuditInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
