"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_fwlog_policy import MonitoringFwlogPolicy
globals()['MonitoringFwlogPolicy'] = MonitoringFwlogPolicy
from pensando_dss.psm.psm.model.monitoring_auto_msg_fwlog_policy_watch_helper_watch_event import MonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent


class TestMonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent(unittest.TestCase):
    """MonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent(self):
        """Test MonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAutoMsgFwlogPolicyWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
