"""
    Diagnostics API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.diagnostics_module_spec import DiagnosticsModuleSpec


class TestDiagnosticsModuleSpec(unittest.TestCase):
    """DiagnosticsModuleSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiagnosticsModuleSpec(self):
        """Test DiagnosticsModuleSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiagnosticsModuleSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
