"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.security_traffic_encryption_policy import SecurityTrafficEncryptionPolicy
globals()['ApiListMeta'] = ApiListMeta
globals()['SecurityTrafficEncryptionPolicy'] = SecurityTrafficEncryptionPolicy
from pensando_dss.psm.psm.model.security_traffic_encryption_policy_list import SecurityTrafficEncryptionPolicyList


class TestSecurityTrafficEncryptionPolicyList(unittest.TestCase):
    """SecurityTrafficEncryptionPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityTrafficEncryptionPolicyList(self):
        """Test SecurityTrafficEncryptionPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityTrafficEncryptionPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
