"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_configuration_issues import ApiConfigurationIssues
from pensando_dss.psm.model.security_ip_sec_rule_status import SecurityIPSecRuleStatus
from pensando_dss.psm.model.security_propagation_status import SecurityPropagationStatus
from pensando_dss.psm.model.security_tunnel_endpoint_status import SecurityTunnelEndpointStatus
globals()['ApiConfigurationIssues'] = ApiConfigurationIssues
globals()['SecurityIPSecRuleStatus'] = SecurityIPSecRuleStatus
globals()['SecurityPropagationStatus'] = SecurityPropagationStatus
globals()['SecurityTunnelEndpointStatus'] = SecurityTunnelEndpointStatus
from pensando_dss.psm.psm.model.security_ip_sec_policy_status import SecurityIPSecPolicyStatus


class TestSecurityIPSecPolicyStatus(unittest.TestCase):
    """SecurityIPSecPolicyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityIPSecPolicyStatus(self):
        """Test SecurityIPSecPolicyStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityIPSecPolicyStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
