"""
    Staging API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.staging_clear_action_status import StagingClearActionStatus


class TestStagingClearActionStatus(unittest.TestCase):
    """StagingClearActionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStagingClearActionStatus(self):
        """Test StagingClearActionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StagingClearActionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
