"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.cluster_tenant import ClusterTenant
globals()['ApiListMeta'] = ApiListMeta
globals()['ClusterTenant'] = ClusterTenant
from pensando_dss.psm.psm.model.cluster_tenant_list import ClusterTenantList


class TestClusterTenantList(unittest.TestCase):
    """ClusterTenantList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterTenantList(self):
        """Test ClusterTenantList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterTenantList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
