"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
globals()['ApiObjectMeta'] = ApiObjectMeta
from pensando_dss.psm.psm.model.auth_password_reset_request import AuthPasswordResetRequest


class TestAuthPasswordResetRequest(unittest.TestCase):
    """AuthPasswordResetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthPasswordResetRequest(self):
        """Test AuthPasswordResetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthPasswordResetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
