"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.cluster_cpu_info import ClusterCPUInfo


class TestClusterCPUInfo(unittest.TestCase):
    """ClusterCPUInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterCPUInfo(self):
        """Test ClusterCPUInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterCPUInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
