"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.cluster_cluster_profile import ClusterClusterProfile
globals()['ClusterClusterProfile'] = ClusterClusterProfile
from pensando_dss.psm.psm.model.cluster_auto_msg_cluster_profile_watch_helper_watch_event import ClusterAutoMsgClusterProfileWatchHelperWatchEvent


class TestClusterAutoMsgClusterProfileWatchHelperWatchEvent(unittest.TestCase):
    """ClusterAutoMsgClusterProfileWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterAutoMsgClusterProfileWatchHelperWatchEvent(self):
        """Test ClusterAutoMsgClusterProfileWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterAutoMsgClusterProfileWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
