"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_dss
from pensando_dss.psm_dss.model.network_policer_profile import NetworkPolicerProfile
globals()['NetworkPolicerProfile'] = NetworkPolicerProfile
from pensando_dss.psm_dss.psm_dss.model.network_auto_msg_policer_profile_watch_helper_watch_event import NetworkAutoMsgPolicerProfileWatchHelperWatchEvent


class TestNetworkAutoMsgPolicerProfileWatchHelperWatchEvent(unittest.TestCase):
    """NetworkAutoMsgPolicerProfileWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkAutoMsgPolicerProfileWatchHelperWatchEvent(self):
        """Test NetworkAutoMsgPolicerProfileWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkAutoMsgPolicerProfileWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
