"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.cluster_flow_export_policy_ref import ClusterFlowExportPolicyRef
from pensando_dss.psm.model.cluster_fwlog_policy_ref import ClusterFwlogPolicyRef
from pensando_dss.psm.model.cluster_ip_config import ClusterIPConfig
from pensando_dss.psm.model.cluster_policer_ref import ClusterPolicerRef
globals()['ClusterFlowExportPolicyRef'] = ClusterFlowExportPolicyRef
globals()['ClusterFwlogPolicyRef'] = ClusterFwlogPolicyRef
globals()['ClusterIPConfig'] = ClusterIPConfig
globals()['ClusterPolicerRef'] = ClusterPolicerRef
from pensando_dss.psm.psm.model.cluster_distributed_service_entity_spec import ClusterDistributedServiceEntitySpec


class TestClusterDistributedServiceEntitySpec(unittest.TestCase):
    """ClusterDistributedServiceEntitySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterDistributedServiceEntitySpec(self):
        """Test ClusterDistributedServiceEntitySpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterDistributedServiceEntitySpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
