"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
globals()['ApiObjectMeta'] = ApiObjectMeta
from pensando_dss.psm.psm.model.cluster_cluster_auth_bootstrap_request import ClusterClusterAuthBootstrapRequest


class TestClusterClusterAuthBootstrapRequest(unittest.TestCase):
    """ClusterClusterAuthBootstrapRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterClusterAuthBootstrapRequest(self):
        """Test ClusterClusterAuthBootstrapRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterClusterAuthBootstrapRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
