"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.network_pause_spec import NetworkPauseSpec


class TestNetworkPauseSpec(unittest.TestCase):
    """NetworkPauseSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkPauseSpec(self):
        """Test NetworkPauseSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkPauseSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
