"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.monitoring_audit_policy import MonitoringAuditPolicy
globals()['ApiListMeta'] = ApiListMeta
globals()['MonitoringAuditPolicy'] = MonitoringAuditPolicy
from pensando_dss.psm.psm.model.monitoring_audit_policy_list import MonitoringAuditPolicyList


class TestMonitoringAuditPolicyList(unittest.TestCase):
    """MonitoringAuditPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAuditPolicyList(self):
        """Test MonitoringAuditPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAuditPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
