"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.security_auto_msg_app_watch_helper_watch_event import SecurityAutoMsgAppWatchHelperWatchEvent
globals()['SecurityAutoMsgAppWatchHelperWatchEvent'] = SecurityAutoMsgAppWatchHelperWatchEvent
from pensando_dss.psm.psm.model.security_auto_msg_app_watch_helper import SecurityAutoMsgAppWatchHelper


class TestSecurityAutoMsgAppWatchHelper(unittest.TestCase):
    """SecurityAutoMsgAppWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityAutoMsgAppWatchHelper(self):
        """Test SecurityAutoMsgAppWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityAutoMsgAppWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
