"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_tech_support_node_result import MonitoringTechSupportNodeResult
globals()['MonitoringTechSupportNodeResult'] = MonitoringTechSupportNodeResult
from pensando_dss.psm.psm.model.monitoring_tech_support_request_status import MonitoringTechSupportRequestStatus


class TestMonitoringTechSupportRequestStatus(unittest.TestCase):
    """MonitoringTechSupportRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringTechSupportRequestStatus(self):
        """Test MonitoringTechSupportRequestStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringTechSupportRequestStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
