"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.labels_selector import LabelsSelector
globals()['LabelsSelector'] = LabelsSelector
from pensando_dss.psm.psm.model.tech_support_request_spec_node_selector_spec import TechSupportRequestSpecNodeSelectorSpec


class TestTechSupportRequestSpecNodeSelectorSpec(unittest.TestCase):
    """TechSupportRequestSpecNodeSelectorSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTechSupportRequestSpecNodeSelectorSpec(self):
        """Test TechSupportRequestSpecNodeSelectorSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TechSupportRequestSpecNodeSelectorSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
