"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.cluster_tenant_spec import ClusterTenantSpec


class TestClusterTenantSpec(unittest.TestCase):
    """ClusterTenantSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterTenantSpec(self):
        """Test ClusterTenantSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterTenantSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
