"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.network_nat_address import NetworkNATAddress


class TestNetworkNATAddress(unittest.TestCase):
    """NetworkNATAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkNATAddress(self):
        """Test NetworkNATAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkNATAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
