"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_auto_msg_audit_policy_watch_helper_watch_event import MonitoringAutoMsgAuditPolicyWatchHelperWatchEvent
globals()['MonitoringAutoMsgAuditPolicyWatchHelperWatchEvent'] = MonitoringAutoMsgAuditPolicyWatchHelperWatchEvent
from pensando_dss.psm.psm.model.monitoring_auto_msg_audit_policy_watch_helper import MonitoringAutoMsgAuditPolicyWatchHelper


class TestMonitoringAutoMsgAuditPolicyWatchHelper(unittest.TestCase):
    """MonitoringAutoMsgAuditPolicyWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAutoMsgAuditPolicyWatchHelper(self):
        """Test MonitoringAutoMsgAuditPolicyWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAutoMsgAuditPolicyWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
