"""
    Browser API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
globals()['ApiObjectMeta'] = ApiObjectMeta
from pensando_dss.psm.psm.model.browser_browse_request import BrowserBrowseRequest


class TestBrowserBrowseRequest(unittest.TestCase):
    """BrowserBrowseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrowserBrowseRequest(self):
        """Test BrowserBrowseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BrowserBrowseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
