"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
globals()['ApiObjectMeta'] = ApiObjectMeta
from pensando_dss.psm.psm.model.monitoring_cancel_archive_request import MonitoringCancelArchiveRequest


class TestMonitoringCancelArchiveRequest(unittest.TestCase):
    """MonitoringCancelArchiveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringCancelArchiveRequest(self):
        """Test MonitoringCancelArchiveRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringCancelArchiveRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
