"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.auth_tls_options import AuthTLSOptions
globals()['AuthTLSOptions'] = AuthTLSOptions
from pensando_dss.psm.psm.model.auth_ldap_server import AuthLdapServer


class TestAuthLdapServer(unittest.TestCase):
    """AuthLdapServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthLdapServer(self):
        """Test AuthLdapServer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthLdapServer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
