"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_auto_msg_alert_policy_watch_helper_watch_event import MonitoringAutoMsgAlertPolicyWatchHelperWatchEvent
globals()['MonitoringAutoMsgAlertPolicyWatchHelperWatchEvent'] = MonitoringAutoMsgAlertPolicyWatchHelperWatchEvent
from pensando_dss.psm.psm.model.monitoring_auto_msg_alert_policy_watch_helper import MonitoringAutoMsgAlertPolicyWatchHelper


class TestMonitoringAutoMsgAlertPolicyWatchHelper(unittest.TestCase):
    """MonitoringAutoMsgAlertPolicyWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAutoMsgAlertPolicyWatchHelper(self):
        """Test MonitoringAutoMsgAlertPolicyWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAutoMsgAlertPolicyWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
