"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.cluster_auto_msg_dsc_profile_watch_helper_watch_event import ClusterAutoMsgDSCProfileWatchHelperWatchEvent
globals()['ClusterAutoMsgDSCProfileWatchHelperWatchEvent'] = ClusterAutoMsgDSCProfileWatchHelperWatchEvent
from pensando_dss.psm.psm.model.cluster_auto_msg_dsc_profile_watch_helper import ClusterAutoMsgDSCProfileWatchHelper


class TestClusterAutoMsgDSCProfileWatchHelper(unittest.TestCase):
    """ClusterAutoMsgDSCProfileWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterAutoMsgDSCProfileWatchHelper(self):
        """Test ClusterAutoMsgDSCProfileWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterAutoMsgDSCProfileWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
