"""
    Staging API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.staging_auto_msg_buffer_watch_helper_watch_event import StagingAutoMsgBufferWatchHelperWatchEvent
globals()['StagingAutoMsgBufferWatchHelperWatchEvent'] = StagingAutoMsgBufferWatchHelperWatchEvent
from pensando_dss.psm.psm.model.staging_auto_msg_buffer_watch_helper import StagingAutoMsgBufferWatchHelper


class TestStagingAutoMsgBufferWatchHelper(unittest.TestCase):
    """StagingAutoMsgBufferWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStagingAutoMsgBufferWatchHelper(self):
        """Test StagingAutoMsgBufferWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StagingAutoMsgBufferWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
