"""
    Sysruntime API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.sysruntime_flow_key_l2 import SysruntimeFlowKeyL2


class TestSysruntimeFlowKeyL2(unittest.TestCase):
    """SysruntimeFlowKeyL2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSysruntimeFlowKeyL2(self):
        """Test SysruntimeFlowKeyL2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SysruntimeFlowKeyL2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
