"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.security_dns import SecurityDns


class TestSecurityDns(unittest.TestCase):
    """SecurityDns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityDns(self):
        """Test SecurityDns"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityDns()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
