"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.network_policer_profile import NetworkPolicerProfile
globals()['ApiListMeta'] = ApiListMeta
globals()['NetworkPolicerProfile'] = NetworkPolicerProfile
from pensando_dss.psm.psm.model.network_policer_profile_list import NetworkPolicerProfileList


class TestNetworkPolicerProfileList(unittest.TestCase):
    """NetworkPolicerProfileList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkPolicerProfileList(self):
        """Test NetworkPolicerProfileList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkPolicerProfileList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
