"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.auth_ldap_attribute_mapping import AuthLdapAttributeMapping


class TestAuthLdapAttributeMapping(unittest.TestCase):
    """AuthLdapAttributeMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthLdapAttributeMapping(self):
        """Test AuthLdapAttributeMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthLdapAttributeMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
