"""
    Sysruntime API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.sysruntime_workload_selector import SysruntimeWorkloadSelector


class TestSysruntimeWorkloadSelector(unittest.TestCase):
    """SysruntimeWorkloadSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSysruntimeWorkloadSelector(self):
        """Test SysruntimeWorkloadSelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SysruntimeWorkloadSelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
