"""
    Search API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.search_policy_search_request import SearchPolicySearchRequest


class TestSearchPolicySearchRequest(unittest.TestCase):
    """SearchPolicySearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchPolicySearchRequest(self):
        """Test SearchPolicySearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchPolicySearchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
