"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.security_firewall_profile import SecurityFirewallProfile
globals()['SecurityFirewallProfile'] = SecurityFirewallProfile
from pensando_dss.psm.psm.model.security_auto_msg_firewall_profile_watch_helper_watch_event import SecurityAutoMsgFirewallProfileWatchHelperWatchEvent


class TestSecurityAutoMsgFirewallProfileWatchHelperWatchEvent(unittest.TestCase):
    """SecurityAutoMsgFirewallProfileWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityAutoMsgFirewallProfileWatchHelperWatchEvent(self):
        """Test SecurityAutoMsgFirewallProfileWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityAutoMsgFirewallProfileWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
