"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.auth_radius_domain import AuthRadiusDomain
globals()['AuthRadiusDomain'] = AuthRadiusDomain
from pensando_dss.psm.psm.model.auth_radius import AuthRadius


class TestAuthRadius(unittest.TestCase):
    """AuthRadius unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthRadius(self):
        """Test AuthRadius"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthRadius()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
