"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.cluster_auto_msg_snapshot_restore_watch_helper_watch_event import ClusterAutoMsgSnapshotRestoreWatchHelperWatchEvent
globals()['ClusterAutoMsgSnapshotRestoreWatchHelperWatchEvent'] = ClusterAutoMsgSnapshotRestoreWatchHelperWatchEvent
from pensando_dss.psm.psm.model.cluster_auto_msg_snapshot_restore_watch_helper import ClusterAutoMsgSnapshotRestoreWatchHelper


class TestClusterAutoMsgSnapshotRestoreWatchHelper(unittest.TestCase):
    """ClusterAutoMsgSnapshotRestoreWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterAutoMsgSnapshotRestoreWatchHelper(self):
        """Test ClusterAutoMsgSnapshotRestoreWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterAutoMsgSnapshotRestoreWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
