"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.auth_user_preference_spec import AuthUserPreferenceSpec


class TestAuthUserPreferenceSpec(unittest.TestCase):
    """AuthUserPreferenceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthUserPreferenceSpec(self):
        """Test AuthUserPreferenceSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthUserPreferenceSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
