"""
    Orchestration API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.orchestration_orchestrator_status import OrchestrationOrchestratorStatus


class TestOrchestrationOrchestratorStatus(unittest.TestCase):
    """OrchestrationOrchestratorStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrchestrationOrchestratorStatus(self):
        """Test OrchestrationOrchestratorStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrchestrationOrchestratorStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
