"""
    Search API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.search_entry_list import SearchEntryList
globals()['SearchEntryList'] = SearchEntryList
from pensando_dss.psm.psm.model.search_kind_aggregation import SearchKindAggregation


class TestSearchKindAggregation(unittest.TestCase):
    """SearchKindAggregation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchKindAggregation(self):
        """Test SearchKindAggregation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchKindAggregation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
