"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.monitoring_threshold import MonitoringThreshold


class TestMonitoringThreshold(unittest.TestCase):
    """MonitoringThreshold unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringThreshold(self):
        """Test MonitoringThreshold"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringThreshold()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
