"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.network_interface_ip import NetworkInterfaceIP


class TestNetworkInterfaceIP(unittest.TestCase):
    """NetworkInterfaceIP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkInterfaceIP(self):
        """Test NetworkInterfaceIP"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkInterfaceIP()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
