"""
    Diagnostics API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_dss
from pensando_dss.psm_dss.model.api_list_meta import ApiListMeta
from pensando_dss.psm_dss.model.diagnostics_module import DiagnosticsModule
globals()['ApiListMeta'] = ApiListMeta
globals()['DiagnosticsModule'] = DiagnosticsModule
from pensando_dss.psm_dss.psm_dss.model.diagnostics_module_list import DiagnosticsModuleList


class TestDiagnosticsModuleList(unittest.TestCase):
    """DiagnosticsModuleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiagnosticsModuleList(self):
        """Test DiagnosticsModuleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiagnosticsModuleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
