"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.monitoring_email_export import MonitoringEmailExport


class TestMonitoringEmailExport(unittest.TestCase):
    """MonitoringEmailExport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringEmailExport(self):
        """Test MonitoringEmailExport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringEmailExport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
