"""
    Search API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.search_policy_match_entries import SearchPolicyMatchEntries
globals()['SearchPolicyMatchEntries'] = SearchPolicyMatchEntries
from pensando_dss.psm.psm.model.search_rules_by_policy_name import SearchRulesByPolicyName


class TestSearchRulesByPolicyName(unittest.TestCase):
    """SearchRulesByPolicyName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchRulesByPolicyName(self):
        """Test SearchRulesByPolicyName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SearchRulesByPolicyName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
