"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.network_auto_msg_network_watch_helper_watch_event import NetworkAutoMsgNetworkWatchHelperWatchEvent
globals()['NetworkAutoMsgNetworkWatchHelperWatchEvent'] = NetworkAutoMsgNetworkWatchHelperWatchEvent
from pensando_dss.psm.psm.model.network_auto_msg_network_watch_helper import NetworkAutoMsgNetworkWatchHelper


class TestNetworkAutoMsgNetworkWatchHelper(unittest.TestCase):
    """NetworkAutoMsgNetworkWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkAutoMsgNetworkWatchHelper(self):
        """Test NetworkAutoMsgNetworkWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkAutoMsgNetworkWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
