"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.auth_role_binding import AuthRoleBinding
globals()['AuthRoleBinding'] = AuthRoleBinding
from pensando_dss.psm.psm.model.auth_auto_msg_role_binding_watch_helper_watch_event import AuthAutoMsgRoleBindingWatchHelperWatchEvent


class TestAuthAutoMsgRoleBindingWatchHelperWatchEvent(unittest.TestCase):
    """AuthAutoMsgRoleBindingWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthAutoMsgRoleBindingWatchHelperWatchEvent(self):
        """Test AuthAutoMsgRoleBindingWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthAutoMsgRoleBindingWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
