"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
from pensando_dss.psm.model.network_virtual_router_peering_group_spec import NetworkVirtualRouterPeeringGroupSpec
from pensando_dss.psm.model.network_virtual_router_peering_group_status import NetworkVirtualRouterPeeringGroupStatus
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['NetworkVirtualRouterPeeringGroupSpec'] = NetworkVirtualRouterPeeringGroupSpec
globals()['NetworkVirtualRouterPeeringGroupStatus'] = NetworkVirtualRouterPeeringGroupStatus
from pensando_dss.psm.psm.model.network_virtual_router_peering_group import NetworkVirtualRouterPeeringGroup


class TestNetworkVirtualRouterPeeringGroup(unittest.TestCase):
    """NetworkVirtualRouterPeeringGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkVirtualRouterPeeringGroup(self):
        """Test NetworkVirtualRouterPeeringGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkVirtualRouterPeeringGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
