"""
    Security API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.security_certificate_status import SecurityCertificateStatus


class TestSecurityCertificateStatus(unittest.TestCase):
    """SecurityCertificateStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityCertificateStatus(self):
        """Test SecurityCertificateStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityCertificateStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
