"""
    Diagnostics API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
from pensando_dss.psm.model.diagnostics_service_port import DiagnosticsServicePort
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['DiagnosticsServicePort'] = DiagnosticsServicePort
from pensando_dss.psm.psm.model.diagnostics_diagnostics_request import DiagnosticsDiagnosticsRequest


class TestDiagnosticsDiagnosticsRequest(unittest.TestCase):
    """DiagnosticsDiagnosticsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiagnosticsDiagnosticsRequest(self):
        """Test DiagnosticsDiagnosticsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiagnosticsDiagnosticsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
