"""
    Objstore API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.objstore_object_status import ObjstoreObjectStatus


class TestObjstoreObjectStatus(unittest.TestCase):
    """ObjstoreObjectStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjstoreObjectStatus(self):
        """Test ObjstoreObjectStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjstoreObjectStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
