"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_object_meta import ApiObjectMeta
from pensando_dss.psm.model.network_nat_policy_spec import NetworkNATPolicySpec
from pensando_dss.psm.model.network_nat_policy_status import NetworkNATPolicyStatus
globals()['ApiObjectMeta'] = ApiObjectMeta
globals()['NetworkNATPolicySpec'] = NetworkNATPolicySpec
globals()['NetworkNATPolicyStatus'] = NetworkNATPolicyStatus
from pensando_dss.psm.psm.model.network_nat_policy import NetworkNATPolicy


class TestNetworkNATPolicy(unittest.TestCase):
    """NetworkNATPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkNATPolicy(self):
        """Test NetworkNATPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkNATPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
