"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.cluster_version_status import ClusterVersionStatus


class TestClusterVersionStatus(unittest.TestCase):
    """ClusterVersionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterVersionStatus(self):
        """Test ClusterVersionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterVersionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
