"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_dss
from pensando_dss.psm_dss.model.api_list_meta import ApiListMeta
from pensando_dss.psm_dss.model.auth_user_preference import AuthUserPreference
globals()['ApiListMeta'] = ApiListMeta
globals()['AuthUserPreference'] = AuthUserPreference
from pensando_dss.psm_dss.psm_dss.model.auth_user_preference_list import AuthUserPreferenceList


class TestAuthUserPreferenceList(unittest.TestCase):
    """AuthUserPreferenceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthUserPreferenceList(self):
        """Test AuthUserPreferenceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthUserPreferenceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
