"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.monitoring_stats_alert_policy import MonitoringStatsAlertPolicy
globals()['ApiListMeta'] = ApiListMeta
globals()['MonitoringStatsAlertPolicy'] = MonitoringStatsAlertPolicy
from pensando_dss.psm.psm.model.monitoring_stats_alert_policy_list import MonitoringStatsAlertPolicyList


class TestMonitoringStatsAlertPolicyList(unittest.TestCase):
    """MonitoringStatsAlertPolicyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringStatsAlertPolicyList(self):
        """Test MonitoringStatsAlertPolicyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringStatsAlertPolicyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
