"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.cluster_pnic_info import ClusterPnicInfo


class TestClusterPnicInfo(unittest.TestCase):
    """ClusterPnicInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterPnicInfo(self):
        """Test ClusterPnicInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterPnicInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
