"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_mirror_export_config import MonitoringMirrorExportConfig
globals()['MonitoringMirrorExportConfig'] = MonitoringMirrorExportConfig
from pensando_dss.psm.psm.model.monitoring_mirror_collector import MonitoringMirrorCollector


class TestMonitoringMirrorCollector(unittest.TestCase):
    """MonitoringMirrorCollector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringMirrorCollector(self):
        """Test MonitoringMirrorCollector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringMirrorCollector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
