"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_proto_port import ApiProtoPort
from pensando_dss.psm.model.network_nat_address import NetworkNATAddress
globals()['ApiProtoPort'] = ApiProtoPort
globals()['NetworkNATAddress'] = NetworkNATAddress
from pensando_dss.psm.psm.model.network_nat_rule import NetworkNATRule


class TestNetworkNATRule(unittest.TestCase):
    """NetworkNATRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkNATRule(self):
        """Test NetworkNATRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkNATRule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
