"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.security_dsc_status import SecurityDSCStatus


class TestSecurityDSCStatus(unittest.TestCase):
    """SecurityDSCStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecurityDSCStatus(self):
        """Test SecurityDSCStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecurityDSCStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
