"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.cluster_auto_msg_license_watch_helper_watch_event import ClusterAutoMsgLicenseWatchHelperWatchEvent
globals()['ClusterAutoMsgLicenseWatchHelperWatchEvent'] = ClusterAutoMsgLicenseWatchHelperWatchEvent
from pensando_dss.psm.psm.model.cluster_auto_msg_license_watch_helper import ClusterAutoMsgLicenseWatchHelper


class TestClusterAutoMsgLicenseWatchHelper(unittest.TestCase):
    """ClusterAutoMsgLicenseWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterAutoMsgLicenseWatchHelper(self):
        """Test ClusterAutoMsgLicenseWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterAutoMsgLicenseWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
