"""
    Staging API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.staging_buffer import StagingBuffer
globals()['StagingBuffer'] = StagingBuffer
from pensando_dss.psm.psm.model.staging_auto_msg_buffer_watch_helper_watch_event import StagingAutoMsgBufferWatchHelperWatchEvent


class TestStagingAutoMsgBufferWatchHelperWatchEvent(unittest.TestCase):
    """StagingAutoMsgBufferWatchHelperWatchEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStagingAutoMsgBufferWatchHelperWatchEvent(self):
        """Test StagingAutoMsgBufferWatchHelperWatchEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StagingAutoMsgBufferWatchHelperWatchEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
