"""
    Workload API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_dse_status import ApiDSEStatus
globals()['ApiDSEStatus'] = ApiDSEStatus
from pensando_dss.psm.psm.model.workload_endpoint_prop_status import WorkloadEndpointPropStatus


class TestWorkloadEndpointPropStatus(unittest.TestCase):
    """WorkloadEndpointPropStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkloadEndpointPropStatus(self):
        """Test WorkloadEndpointPropStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkloadEndpointPropStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
