"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.network_policer_action import NetworkPolicerAction
from pensando_dss.psm.model.network_policer_criteria import NetworkPolicerCriteria
globals()['NetworkPolicerAction'] = NetworkPolicerAction
globals()['NetworkPolicerCriteria'] = NetworkPolicerCriteria
from pensando_dss.psm.psm.model.network_policer_profile_spec import NetworkPolicerProfileSpec


class TestNetworkPolicerProfileSpec(unittest.TestCase):
    """NetworkPolicerProfileSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkPolicerProfileSpec(self):
        """Test NetworkPolicerProfileSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkPolicerProfileSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
