"""
    Auth API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.auth_operation_status import AuthOperationStatus
globals()['AuthOperationStatus'] = AuthOperationStatus
from pensando_dss.psm.psm.model.auth_user_status import AuthUserStatus


class TestAuthUserStatus(unittest.TestCase):
    """AuthUserStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthUserStatus(self):
        """Test AuthUserStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthUserStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
