"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.monitoring_auto_msg_troubleshooting_session_watch_helper_watch_event import MonitoringAutoMsgTroubleshootingSessionWatchHelperWatchEvent
globals()['MonitoringAutoMsgTroubleshootingSessionWatchHelperWatchEvent'] = MonitoringAutoMsgTroubleshootingSessionWatchHelperWatchEvent
from pensando_dss.psm.psm.model.monitoring_auto_msg_troubleshooting_session_watch_helper import MonitoringAutoMsgTroubleshootingSessionWatchHelper


class TestMonitoringAutoMsgTroubleshootingSessionWatchHelper(unittest.TestCase):
    """MonitoringAutoMsgTroubleshootingSessionWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringAutoMsgTroubleshootingSessionWatchHelper(self):
        """Test MonitoringAutoMsgTroubleshootingSessionWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MonitoringAutoMsgTroubleshootingSessionWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
