"""
    Routing API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.api_list_meta import ApiListMeta
from pensando_dss.psm.model.routing_route import RoutingRoute
globals()['ApiListMeta'] = ApiListMeta
globals()['RoutingRoute'] = RoutingRoute
from pensando_dss.psm.psm.model.routing_route_list import RoutingRouteList


class TestRoutingRouteList(unittest.TestCase):
    """RoutingRouteList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoutingRouteList(self):
        """Test RoutingRouteList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoutingRouteList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
