"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.network_auto_msg_ip_collection_watch_helper_watch_event import NetworkAutoMsgIPCollectionWatchHelperWatchEvent
globals()['NetworkAutoMsgIPCollectionWatchHelperWatchEvent'] = NetworkAutoMsgIPCollectionWatchHelperWatchEvent
from pensando_dss.psm.psm.model.network_auto_msg_ip_collection_watch_helper import NetworkAutoMsgIPCollectionWatchHelper


class TestNetworkAutoMsgIPCollectionWatchHelper(unittest.TestCase):
    """NetworkAutoMsgIPCollectionWatchHelper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkAutoMsgIPCollectionWatchHelper(self):
        """Test NetworkAutoMsgIPCollectionWatchHelper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkAutoMsgIPCollectionWatchHelper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
