"""
    Preferences API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.preferences_idle_timeout import PreferencesIdleTimeout
globals()['PreferencesIdleTimeout'] = PreferencesIdleTimeout
from pensando_dss.psm.psm.model.preferences_ui_global_settings_spec import PreferencesUIGlobalSettingsSpec


class TestPreferencesUIGlobalSettingsSpec(unittest.TestCase):
    """PreferencesUIGlobalSettingsSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferencesUIGlobalSettingsSpec(self):
        """Test PreferencesUIGlobalSettingsSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PreferencesUIGlobalSettingsSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
