"""
    Monitoring API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.fields_requirement import FieldsRequirement
globals()['FieldsRequirement'] = FieldsRequirement
from pensando_dss.psm.psm.model.fields_selector import FieldsSelector


class TestFieldsSelector(unittest.TestCase):
    """FieldsSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldsSelector(self):
        """Test FieldsSelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldsSelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
