"""
    Objstore API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.psm.model.objstore_object_spec import ObjstoreObjectSpec


class TestObjstoreObjectSpec(unittest.TestCase):
    """ObjstoreObjectSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjstoreObjectSpec(self):
        """Test ObjstoreObjectSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjstoreObjectSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
