"""
    Network API reference

       # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm_dss
from pensando_dss.psm_dss.model.network_route_distinguisher import NetworkRouteDistinguisher
globals()['NetworkRouteDistinguisher'] = NetworkRouteDistinguisher
from pensando_dss.psm_dss.psm_dss.model.network_rd_spec import NetworkRDSpec


class TestNetworkRDSpec(unittest.TestCase):
    """NetworkRDSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkRDSpec(self):
        """Test NetworkRDSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkRDSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
