"""
    Cluster API reference

    Service name    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import psm
from pensando_dss.psm.model.recoverykeys_recovery_keys import RecoverykeysRecoveryKeys
globals()['RecoverykeysRecoveryKeys'] = RecoverykeysRecoveryKeys
from pensando_dss.psm.psm.model.cluster_cluster_spec import ClusterClusterSpec


class TestClusterClusterSpec(unittest.TestCase):
    """ClusterClusterSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterClusterSpec(self):
        """Test ClusterClusterSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterClusterSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
